package io.phasetwo.service.resource;

public enum OrganizationResourceType {
  ORGANIZATION,
  ORGANIZATION_MEMBERSHIP,
  ORGANIZATION_ROLE,
  ORGANIZATION_ROLE_MAPPING,
  TEAM,
  TEAM_MEMBERSHIP,
  INVITATION,
  ORGANIZATION_GROUP,
  ORGANIZATION_GROUP_MEMBERSHIP,
  ORGANIZATION_GROUP_ROLE_MAPPING;
}
